parsed the object to frontend, to implement conversion
mcgill-robotics/rover pull request #140
Opened 2024-02-03 04:00 UTC by Blacklotus89898

2024-02-16 21:59 UTC, amotaouakkil123 requested changes

2024-02-16 21:59 UTC, amotaouakkil123 commented on angular_ui_app/src/app/components/drive/drive.component.ts
> +  euler_from_quaternion(x: number, y: number, z: number, w: number) {
Why is this function necessary? Do we not have an IMU with known units? It seems unnecessary to put it in drive too.

2024-02-16 21:59 UTC, amotaouakkil123 commented on angular_ui_app/src/app/app.component.html
> +    <!-- navbar in header -->
Are we waiting for more in this app part?

2024-02-16 21:59 UTC, amotaouakkil123 commented on angular_ui_app/src/app/components/navbar/navbar.component.html
> +<div class="navbar" style="flex-wrap: wrap; align-content: space-around; padding: 0 10%;">
What is implied by navbar? The rest of the names are understood, but I can't seem to get what navbar means?

2024-02-25 17:14 UTC, JosephSaliba01 commented
@Blacklotus89898 Could you explain what this PR is for

2024-02-25 17:51 UTC, Blacklotus89898 commented on angular_ui_app/src/app/components/drive/drive.component.ts
> +  euler_from_quaternion(x: number, y: number, z: number, w: number) {
I think it was previously used in the old UI. There might be chance that it's no longer used.

2024-02-25 17:51 UTC, Blacklotus89898 commented on angular_ui_app/src/app/app.component.html
> +    <!-- navbar in header -->
I think I only left this comment to remind me that the navbar is moved to header.

2024-02-25 17:53 UTC, Blacklotus89898 commented on angular_ui_app/src/app/components/navbar/navbar.component.html
> +<div class="navbar" style="flex-wrap: wrap; align-content: space-around; padding: 0 10%;">
Header is only a container at the top of the UI, while the navbar is the component that has all the clickable links to change pages/views. Essentially, the navbar could be on top (inisde header) or on the side.

2024-02-25 17:55 UTC, Blacklotus89898 commented
> @Blacklotus89898 Could you explain what this PR is for

This was initially used as a draft PR to see how much it diverged from the angular-ui and it has a lot of deprecated features to be deleted. I'm thinking about deleting it (once I do a proper review it). It will have to wait after my last midterm this Monday.

2024-02-25 18:01 UTC, amotaouakkil123 commented on angular_ui_app/src/app/components/drive/drive.component.ts
> +  euler_from_quaternion(x: number, y: number, z: number, w: number) {
We don't need it anymore.

2024-02-25 18:01 UTC, amotaouakkil123 commented on angular_ui_app/src/app/app.component.html
> +    <!-- navbar in header -->
Remove from PR branch if it is just a local reminder.

2024-02-25 18:02 UTC, amotaouakkil123 commented on angular_ui_app/src/app/components/navbar/navbar.component.html
> +<div class="navbar" style="flex-wrap: wrap; align-content: space-around; padding: 0 10%;">
Ok, so this PR is still not done as navbar should be a greater part of the UI skeleton right?

2024-02-25 18:03 UTC, amotaouakkil123 commented
> > @Blacklotus89898 Could you explain what this PR is for
> 
> This was initially used as a draft PR to see how much it diverged from the angular-ui and it has a lot of deprecated features to be deleted. I'm thinking about deleting it (once I do a proper review it). It will have to wait after my last midterm this Monday.

Sounds good, thanks for the update. please make sure you go through a quick task draft up for the meeting on Tuesday. Shouldn't take you more than 20 minutes.

2024-02-25 18:05 UTC, Blacklotus89898 commented
> > > @Blacklotus89898 Could you explain what this PR is for
> > 
> > 
> > This was initially used as a draft PR to see how much it diverged from the angular-ui and it has a lot of deprecated features to be deleted. I'm thinking about deleting it (once I do a proper review it). It will have to wait after my last midterm this Monday.
> 
> Sounds good, thanks for the update. please make sure you go through a quick task draft up for the meeting on Tuesday. Shouldn't take you more than 20 minutes.

Just to be sure, you want me to like prepare a plan/list of priority of the task to come for UI right?

2024-02-25 18:25 UTC, amotaouakkil123 commented
> > > > @Blacklotus89898 Could you explain what this PR is for
> > > 
> > > 
> > > This was initially used as a draft PR to see how much it diverged from the angular-ui and it has a lot of deprecated features to be deleted. I'm thinking about deleting it (once I do a proper review it). It will have to wait after my last midterm this Monday.
> > 
> > 
> > Sounds good, thanks for the update. please make sure you go through a quick task draft up for the meeting on Tuesday. Shouldn't take you more than 20 minutes.
> 
> Just to be sure, you want me to like prepare a plan/list of priority of the task to come for UI right?

Yes, so that your intended review and progress from this PR does not go to waste and so that members have some meat to chew on.

2024-02-25 20:57 UTC, Blacklotus89898 commented
> > > > > @Blacklotus89898 Could you explain what this PR is for
> > > > 
> > > > 
> > > > This was initially used as a draft PR to see how much it diverged from the angular-ui and it has a lot of deprecated features to be deleted. I'm thinking about deleting it (once I do a proper review it). It will have to wait after my last midterm this Monday.
> > > 
> > > 
> > > Sounds good, thanks for the update. please make sure you go through a quick task draft up for the meeting on Tuesday. Shouldn't take you more than 20 minutes.
> > 
> > 
> > Just to be sure, you want me to like prepare a plan/list of priority of the task to come for UI right?
> 
> Yes, so that your intended review and progress from this PR does not go to waste and so that members have some meat to chew on.
Sounds good, thanks

2024-02-28 00:14 UTC, Blacklotus89898 commented on angular_ui_app/src/app/components/navbar/navbar.component.html
> +<div class="navbar" style="flex-wrap: wrap; align-content: space-around; padding: 0 10%;">
Yeah, we could say that I'm making the navbar an individual component that can be reused or moved, and it is currently placed inside the header of the UI.

2024-04-28 02:58 UTC, JosephSaliba01 commented
@Blacklotus89898 Can I close this PR?

2024-04-28 03:00 UTC, Blacklotus89898 commented
> @Blacklotus89898 Can I close this PR?

Yeah I think it's no longer relevant and I can always reimplement the navbar when needed

2024-04-28 14:59 UTC, JosephSaliba01 commented
Closing as changes no longer relevant and can be re-implemented easily later.

2024-04-28 14:59 UTC, closed without merging