Linked Angular Gamepad to cmd vel
mcgill-robotics/rover pull request #143
Opened 2024-02-15 19:52 UTC by JosephSaliba01

2024-02-16 22:11 UTC, amotaouakkil123 requested changes

2024-02-16 22:11 UTC, amotaouakkil123 commented on human_control_interface/src/Controller/Gamepad.py
> -        self.a6 = 0
Remove entire file.

2024-02-17 17:08 UTC, JosephSaliba01 commented on human_control_interface/src/Controller/Gamepad.py
> -        self.a6 = 0
The idea is to keep both for now in case Angular Gamepad fails

2024-02-25 17:12 UTC, JosephSaliba01 commented
For now, merging while keeping old gamepad for testing. We'll clean that up later

2024-02-25 17:12 UTC, merged