Angular UI webrtc into angular-ui
mcgill-robotics/rover pull request #156
Opened 2024-04-27 20:37 UTC by Blacklotus89898

2024-04-27 21:25 UTC, JosephSaliba01 commented on .github/workflows/sanity-check.yml
> -          cuda: '12.1.0'
Why are we removing this?

2024-04-27 21:37 UTC, JosephSaliba01 requested changes
Good other than my question

2024-04-27 21:37 UTC, JosephSaliba01 commented on .github/workflows/sanity-check.yml
> -            ./buildLibrealsense.sh
And this

2024-04-27 21:40 UTC, Blacklotus89898 commented on .github/workflows/sanity-check.yml
> -          cuda: '12.1.0'
I honestly do not why it is being removed. I'm might have overwritten it when merging angular-ui into it before the PR, but I will check how it got changed.

2024-04-27 21:46 UTC, Blacklotus89898 commented on .github/workflows/sanity-check.yml
> -          cuda: '12.1.0'
It was changed when we merged remote tracking into it: b5ab57a771555eeebe8e42227fd7c7895e464aa6
https://github.com/mcgill-robotics/rover/pull/156/commits/0eda0cbd1743e6354d950a5d8cab1e8936586aa1

2024-04-27 22:10 UTC, JosephSaliba01 commented
@Blacklotus89898 I see that you reverted the changes on the workflow file, you sure these changes shouldn't be there? Is it good now?

2024-04-27 22:13 UTC, Blacklotus89898 commented
> @Blacklotus89898 I see that you reverted the changes on the workflow file, you sure these changes shouldn't be there? Is it good now?

I think I should double check with Adam just to be sure regarding that file.

2024-04-28 00:37 UTC, amotaouakkil123 approved these changes

2024-04-28 03:08 UTC, JosephSaliba01 approved these changes

2024-04-28 03:09 UTC, merged