Fixed gazebo simulation and added depth camera
mcgill-robotics/rover pull request #63
Opened 2023-02-01 18:47 UTC by JosephSaliba01

Maybe only review changes done to `drive_control/test/*`, other than that all should be good.

2023-02-03 00:14 UTC, acoulombe approved these changes
Aside from the odd/somewhat descriptive dae file names, everything looks good

2023-02-04 20:57 UTC, acoulombe requested changes
Few things for Adam to fix

2023-02-04 20:57 UTC, acoulombe commented on drive_control/src/drive_control_node.py
>          self.right_front_pid_controller = PID(1, 0.1, 0.05, 0)
Remove these. Deprecated

2023-02-04 20:57 UTC, acoulombe commented on drive_control/src/drive_control_node.py
>  from simple_pid import PID
Remove Line Deprecated

2023-02-04 20:57 UTC, acoulombe commented on drive_control/src/drive_control_node.py
> +        self.basis = self.gkern(kernlen=50)
Have 50 as a variable everywhere

2023-02-04 20:57 UTC, acoulombe commented on drive_control/src/steering.py
> +        if wR > 3.0:
Have min/max as variable that is changeable with input or helper functions

2023-02-05 19:36 UTC, acoulombe approved these changes

2023-02-05 19:47 UTC, Shaswata79 approved these changes

2023-02-05 19:49 UTC, merged