new topic camera controller input + new msg type + cameraProcessCall
mcgill-robotics/rover pull request #66
Opened 2023-03-04 19:25 UTC by WalidAissa

2023-03-05 00:50 UTC, acoulombe reviewed
Looks good already, just some deisgn choice questions

2023-03-05 00:50 UTC, acoulombe commented on CameraData/msg/Camera_Orientation.msg
> +float32 v_angle #Vertical orientation tilt of the camera enclosed in [-20, 20] degrees
angles will be either +/-90 or +/-180. Need to confirm with actual servos

2023-03-05 00:50 UTC, acoulombe commented on human_control_interface/src/Controller/GamepadProcess.py
> +        cam_ctrl.v_angle = ((math.acos(msg.A5) - math.pi/2)/math.pi)*40
this spits a value based on the location of the of the joystick. Do we want to hold the joystick to look at something? we can integrate it to get positions

2023-03-11 21:31 UTC, WalidAissa commented on human_control_interface/src/Controller/GamepadProcess.py
> +        cam_ctrl.v_angle = ((math.acos(msg.A5) - math.pi/2)/math.pi)*40
I made the necessary changes. Let me know if what I did for integration is correct.

2023-04-01 16:37 UTC, acoulombe requested changes

2023-04-01 16:37 UTC, acoulombe commented on human_control_interface/src/Controller/GamepadProcess.py
> +        cam_ctrl.v_angle = (180*msg.A5*math.acos(msg.A5)-180*math.sqrt(1-msg.A5**2))/math.pi - 90*msg.A5
This might have been a confusion in what I meant for an integration of the velocity. Good integral, but no +C (constant) which would have been what keeps it in position. 

Make cam_ctrl a global variable and add the msg.A* to it, with every call it will add/substract the desired shift. Example, if we start at 90 and hold the joystick to remove -1 for 10 calls and 0 for 100 calls, the position will be at 80. Also add a limit check to not add/substrat past the angular limits (0, 180)

2023-04-08 01:43 UTC, WalidAissa commented on human_control_interface/src/Controller/GamepadProcess.py
> +        cam_ctrl.v_angle = (180*msg.A5*math.acos(msg.A5)-180*math.sqrt(1-msg.A5**2))/math.pi - 90*msg.A5
Made other changes, I hope I got what you meant this time.

2023-04-08 23:11 UTC, acoulombe approved these changes

2023-04-10 22:50 UTC, Shaswata79 approved these changes

2023-04-10 22:53 UTC, merged