Made readme
mcgill-robotics/rover pull request #70
Opened 2023-05-13 22:11 UTC by eozturk2

Made readme to document how to get started with the ROS environment

2023-05-16 02:58 UTC, acoulombe requested changes

2023-05-16 02:58 UTC, acoulombe commented on README.md
> +Navigate to the folder into which you cloned this repo, and run `catkin_make`. This should build the modules and
we don't use the `catkin_make` build structure. We use the subtly different ` catkin make`, which gives better development tools than the prior underscore variant that only builds when the make is invoked

2023-05-16 02:58 UTC, acoulombe commented on README.md
> +`rosrun [package_name] [node_name]`
Also point to the launch files

2023-05-16 02:58 UTC, acoulombe commented on README.md
> +should install pyserial and pybullet for Python.
we have a requirements.txt with all the python packages to install. Better to point to that than each individual package needed

2023-05-16 13:29 UTC, eozturk2 commented on README.md
> +Navigate to the folder into which you cloned this repo, and run `catkin_make`. This should build the modules and
Is it `catkin make` or `catkin build` ?

2023-05-16 13:35 UTC, eozturk2 commented on README.md
> +`rosrun [package_name] [node_name]`
Done

2023-05-16 13:35 UTC, eozturk2 commented on README.md
> +Navigate to the folder into which you cloned this repo, and run `catkin_make`. This should build the modules and
`catkin make` doesn't seem to work on my end

2023-05-16 17:47 UTC, eozturk2 commented on README.md
> +Navigate to the folder into which you cloned this repo, and run `catkin_make`. This should build the modules and
Again, `catkin make` apparently isn't a thing. `catkin init` followed by a `catkin build` does work though. Another thing is that CameraData isn't a ROS module so it looks like we can't import stuff from it in the human control interface. This is what kills the GamepadProcess.py. For now I commented out the parts that need the camera orientation, and Shaswata said that CameraData might need to be another ROS module.

2023-05-16 17:53 UTC, acoulombe commented on README.md
> +Navigate to the folder into which you cloned this repo, and run `catkin_make`. This should build the modules and
just checked again, it is the `catkin init` followed by `catkin build` development flow we are using. My mind is wandering. CameraData will either need to become a package.

2023-05-16 18:03 UTC, eozturk2 commented on README.md
> +Navigate to the folder into which you cloned this repo, and run `catkin_make`. This should build the modules and
Another problem with the launch files is that the embedded bridge doesn't seem to recognize some of the new arm module messages, or something like that. @Shaswata79 can probably clarify better than I can.

2023-06-26 10:47 UTC, eozturk2 commented on README.md
> +Navigate to the folder into which you cloned this repo, and run `catkin_make`. This should build the modules and
Fixed the readme too while I was at it

2023-07-16 23:49 UTC, acoulombe approved these changes

2023-07-20 23:30 UTC, merged