Embedded bridge new
mcgill-robotics/rover pull request #73
Opened 2023-06-11 15:21 UTC by eozturk2

Changed the embedded bridge and serial node to reflect the changes in hardware

2023-06-17 20:58 UTC, acoulombe requested changes

2023-06-17 20:58 UTC, acoulombe commented on arm_control/src/arm_controller.py
> +            print("_________[Control cycle]_________")
No printing in final code

2023-06-17 20:58 UTC, acoulombe commented on embedded_bridge/src/serial_interface.py
>          for i in range(timeout):
change `timeout` to `attempts`, and remove the timeout entirely

2023-06-17 20:58 UTC, acoulombe commented on embedded_bridge/src/serial_interface.py
> +        # # Convert the data to bytes
double comment ....

2023-06-17 20:58 UTC, acoulombe commented on embedded_bridge/src/serial_interface.py
> +        #     # crc = compute_crc8ccitt(crc, ord(packet_id)) Now matches the Arduino algorithm
CRC computations is still required

2023-06-17 20:58 UTC, acoulombe commented on embedded_bridge/src/serial_states.py
> +        self.driveMotorLBSpeed = 0
Comment the type on the side of each variable for more precision 
`self.driveMotorLBSpeed = 0 #int32` for example

2023-06-17 20:58 UTC, acoulombe commented on embedded_bridge/src/serial_states.py
> +        self.clawState = False
claw is a float, we control it's angle (how open it is)

2023-06-17 20:58 UTC, acoulombe commented on embedded_bridge/src/serial_states.py
> +        # payload += short_to_bytes(self.endEffectorPosition)
remove comments of dead code

2023-06-17 20:58 UTC, acoulombe commented on embedded_bridge/src/serial_node.py
> +import matplotlib.pyplot as plt
WHY

2023-06-17 20:58 UTC, acoulombe commented on embedded_bridge/src/serial_node.py
> +        self.port_name = "/dev/ttyACM0"
Make these configurable, can be done through a ROS config file or leave it like this and someone else can do it

2023-06-17 20:58 UTC, acoulombe commented on embedded_bridge/src/serial_node.py
> +        self.serial_buffer = bytearray(87)
Why 87 bytes for the size?

2023-06-17 20:58 UTC, acoulombe commented on embedded_bridge/src/serial_node.py
> -        rospy.on_shutdown(self.releasePorts)
still keep something similar to this mechanism to close ports properly if the node crashes

2023-06-17 20:58 UTC, acoulombe commented on embedded_bridge/src/serial_node.py
> +                if time.time() - t >= self.serial_polling_interval:
Use a rospy.Rate to have to node run every time interval. Saves polling processing time.
```
rate = rospy.Rate(1) # 1 Hz
# Do stuff, maybe in a while loop
rate.sleep() # Sleeps for 1/rate sec
```

2023-06-17 20:58 UTC, acoulombe commented on embedded_bridge/src/serial_node.py
> +                time.sleep(self.serial_polling_interval)
not needed if you do rospy.Rate

2023-06-17 20:58 UTC, acoulombe commented on human_control_interface/src/Controller/GamepadProcess.py
> +# from CameraData.msg import Camera_Orientation
merge main into your branch, this was fixed

2023-06-17 22:29 UTC, eozturk2 commented on embedded_bridge/src/serial_node.py
> +import matplotlib.pyplot as plt
I honestly can't remember why. It's no longer there

2023-06-17 22:30 UTC, eozturk2 commented on embedded_bridge/src/serial_interface.py
> +        #     # crc = compute_crc8ccitt(crc, ord(packet_id)) Now matches the Arduino algorithm
File is no longer used. Will delete in next commit along with the other changes

2023-06-17 22:30 UTC, eozturk2 commented on embedded_bridge/src/serial_interface.py
> +        # # Convert the data to bytes
File is no longer used. Will delete in next commit along with the other changes

2023-06-17 22:30 UTC, eozturk2 commented on embedded_bridge/src/serial_interface.py
>          for i in range(timeout):
File is no longer used. Will delete in next commit along with the other changes

2023-06-17 22:30 UTC, eozturk2 commented on arm_control/src/arm_controller.py
> +            print("_________[Control cycle]_________")
Can I keep the ones in the embedded bridge? I want to see what is being exchanged

2023-06-17 22:36 UTC, eozturk2 commented on embedded_bridge/src/serial_node.py
> +        self.serial_buffer = bytearray(87)
It happened to be the total size of the feedback data. What should the size be?

2023-06-17 22:37 UTC, eozturk2 commented on embedded_bridge/src/serial_node.py
> +        self.port_name = "/dev/ttyACM0"
Not sure how to do that, will look into it

2023-06-17 22:40 UTC, eozturk2 commented on embedded_bridge/src/serial_states.py
> +        self.clawState = False
In that case the arm command message will also need to change. Which branch has the most recent one?

2023-06-17 23:29 UTC, acoulombe commented on arm_control/src/arm_controller.py
> +            print("_________[Control cycle]_________")
if they are behind a verbose flag

2023-06-17 23:30 UTC, acoulombe commented on embedded_bridge/src/serial_node.py
> +        self.serial_buffer = bytearray(87)
make it computable based on data expectation

2023-06-26 10:29 UTC, eozturk2 commented on embedded_bridge/src/serial_node.py
> -        rospy.on_shutdown(self.releasePorts)
Serial port is now closed on exit and exceptions

2023-06-26 10:50 UTC, eozturk2 commented on human_control_interface/src/Controller/GamepadProcess.py
> +# from CameraData.msg import Camera_Orientation
CameraData.msg still can't be found

2023-06-26 11:12 UTC, eozturk2 commented on human_control_interface/src/Controller/GamepadProcess.py
> +# from CameraData.msg import Camera_Orientation
The module is actually named camera_data, not CameraData. Fixed that by renaming the imports

2023-06-26 12:09 UTC, eozturk2 commented on embedded_bridge/src/serial_node.py
> +        self.serial_buffer = bytearray(87)
Not sure what this means

2023-06-26 12:19 UTC, eozturk2 commented on embedded_bridge/src/serial_node.py
> +        self.port_name = "/dev/ttyACM0"
Serial node now looks for YAML config flie, defaults to `/dev/ttyACM0` if not found. [See chat](https://chat.openai.com/?model=gpt-4) for the YAML file format, since I don't know where our config files should live

2023-07-07 10:43 UTC, eozturk2 commented
Branch was made obsolete by a hardware change

2023-07-07 10:43 UTC, closed without merging