Message consolidation
mcgill-robotics/rover pull request #89
Opened 2023-07-30 23:36 UTC by amotaouakkil123

Created the power tab that sends a powerCmd message with the appropriate "power on" messages. Power tab is updated with all the correct messages and the main UI .py file contains all the correct feedback messages alongside the right publishers. 
Need to implement the servo publishers.

2023-07-31 00:02 UTC, Shaswata79 commented on ui_app/src/power_backend.py
> +
Include the servo angles here?

2023-07-31 21:52 UTC, amotaouakkil123 commented on drive_control/src/drive_control_node.py
> +        self.motor_publisher = rospy.Subscriber("/driveCmd", Float32MultiArray, queue_size=1)
It's supposed to be a publisher, I'm publishing straight from the drive_control_node

2023-07-31 21:53 UTC, amotaouakkil123 commented on drive_control/src/drive_control_node.py
>          self.angular_velocity_publisher = rospy.Publisher('/wheel_velocity_cmd', WheelSpeed, queue_size=1)
No I still want to have access to the wheel_velocities before publishing the motor values.

2023-08-08 01:00 UTC, acoulombe requested changes

2023-08-08 03:28 UTC, amotaouakkil123 commented on ui_app/src/power_backend.py
> +        if self.ui.drive_enabled.isChecked():
Is this necessary? I think the function naming is clear enough and also works when testing the ticking of the boxes.

2023-08-08 03:37 UTC, acoulombe commented on ui_app/src/power_backend.py
> +        if self.ui.drive_enabled.isChecked():
It's a suggestion for cleaner code. You can convert the if condition to a simple read

2023-08-10 01:27 UTC, amotaouakkil123 commented on drive_control/src/drive_control_node.py
Btw any changes on drive_control is on Joseph's branch for drive and gamepad process changes.

2023-08-11 01:20 UTC, merged